### ISSUE TITLE
java-maven #5 failed

### ISSUE THREAD

**Issue by ramprasadgk** [ramprasadgk/java-maven#24]
Build 'java-maven' is failing!

Last 50 lines of build output:

```
[...truncated 150.13 KB...]
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus/3.1/plexus-3.1.pom
Progress (1): 4.1/19 kBProgress (1): 7.5/19 kBProgress (1): 12/19 kB Progress (1): 16/19 kBProgress (1): 19 kB                      Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus/3.1/plexus-3.1.pom (19 kB at 405 kB/s)
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom
Progress (1): 1.1 kB                    Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom (1.1 kB at 20 kB/s)
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom
Progress (1): 4.1/5.0 kBProgress (1): 5.0 kB                        Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom (5.0 kB at 237 kB/s)
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom
Progress (1): 3.3/6.4 kBProgress (1): 6.4 kB                        Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom (6.4 kB at 189 kB/s)
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar
Progress (1): 4.1/12 kBProgress (1): 7.5/12 kBProgress (1): 12/12 kB Progress (1): 12 kB                      Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar (12 kB at 320 kB/s)
Progress (1): 4.1/230 kBProgress (1): 7.5/230 kBProgress (1): 12/230 kB Progress (1): 16/230 kBProgress (1): 20/230 kBProgress (1): 24/230 kBProgress (1): 28/230 kBProgress (1): 32/230 kBProgress (1): 36/230 kBProgress (1): 40/230 kBProgress (1): 44/230 kBProgress (1): 48/230 kBProgress (1): 53/230 kBProgress (1): 57/230 kBProgress (1): 61/230 kBProgress (1): 65/230 kBProgress (1): 69/230 kBProgress (1): 73/230 kBProgress (1): 77/230 kBProgress (1): 81/230 kBProgress (1): 85/230 kBProgress (1): 89/230 kBProgress (1): 93/230 kBProgress (1): 98/230 kBProgress (1): 102/230 kBProgress (1): 106/230 kBProgress (1): 110/230 kBProgress (1): 114/230 kBProgress (1): 118/230 kBProgress (1): 122/230 kBProgress (1): 126/230 kBProgress (1): 130/230 kBProgress (1): 134/230 kBProgress (1): 139/230 kBProgress (1): 143/230 kBProgress (1): 147/230 kBProgress (1): 151/230 kBProgress (1): 155/230 kBProgress (1): 159/230 kBProgress (1): 163/230 kBProgress (1): 167/230 kBProgress (1): 171/230 kBProgress (1): 175/230 kBProgress (1): 180/230 kBProgress (1): 184/230 kBProgress (1): 188/230 kBProgress (1): 192/230 kBProgress (1): 196/230 kBProgress (1): 200/230 kBProgress (1): 204/230 kBProgress (1): 208/230 kBProgress (1): 212/230 kBProgress (1): 216/230 kBProgress (1): 220/230 kBProgress (1): 225/230 kBProgress (1): 229/230 kBProgress (1): 230 kB                        Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar (230 kB at 1.6 MB/s)
[main] INFO org.codehaus.plexus.PlexusContainer - Installing /var/jenkins_home/workspace/java-maven/target/java-maven-junit-helloworld-1.0.0-SNAPSHOT.jar to /var/jenkins_home/.m2/repository/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/java-maven-junit-helloworld-1.0.0-SNAPSHOT.jar
[main] INFO org.codehaus.plexus.PlexusContainer - Installing /var/jenkins_home/workspace/java-maven/pom.xml to /var/jenkins_home/.m2/repository/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/java-maven-junit-helloworld-1.0.0-SNAPSHOT.pom
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-deploy-plugin:2.7:deploy (default-deploy) @ java-maven-junit-helloworld ---
Downloading from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar
Progress (1): 4.1/251 kBProgress (1): 7.5/251 kBProgress (1): 12/251 kB Progress (1): 16/251 kBProgress (1): 20/251 kBProgress (1): 24/251 kBProgress (1): 28/251 kBProgress (1): 32/251 kBProgress (1): 36/251 kBProgress (1): 40/251 kBProgress (1): 44/251 kBProgress (1): 48/251 kBProgress (1): 53/251 kBProgress (1): 57/251 kBProgress (1): 61/251 kBProgress (1): 65/251 kBProgress (1): 69/251 kBProgress (1): 73/251 kBProgress (1): 77/251 kBProgress (1): 81/251 kBProgress (1): 85/251 kBProgress (1): 89/251 kBProgress (1): 93/251 kBProgress (1): 98/251 kBProgress (1): 102/251 kBProgress (1): 106/251 kBProgress (1): 110/251 kBProgress (1): 114/251 kBProgress (1): 118/251 kBProgress (1): 122/251 kBProgress (1): 126/251 kBProgress (1): 130/251 kBProgress (1): 134/251 kBProgress (1): 139/251 kBProgress (1): 143/251 kBProgress (1): 147/251 kBProgress (1): 151/251 kBProgress (1): 155/251 kBProgress (1): 159/251 kBProgress (1): 163/251 kBProgress (1): 167/251 kBProgress (1): 171/251 kBProgress (1): 175/251 kBProgress (1): 180/251 kBProgress (1): 184/251 kBProgress (1): 188/251 kBProgress (1): 192/251 kBProgress (1): 196/251 kBProgress (1): 200/251 kBProgress (1): 204/251 kBProgress (1): 208/251 kBProgress (1): 212/251 kBProgress (1): 216/251 kBProgress (1): 220/251 kBProgress (1): 225/251 kBProgress (1): 229/251 kBProgress (1): 233/251 kBProgress (1): 237/251 kBProgress (1): 241/251 kBProgress (1): 245/251 kBProgress (1): 249/251 kBProgress (1): 251 kB                        Downloaded from artifactory-release: http://9.42.24.114:8082/artifactory/ida-virtual/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar (251 kB at 2.4 MB/s)
Downloading from snapshots: http://9.42.24.114:8082/artifactory/ida-virtual/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/maven-metadata.xml
[main] WARNING org.codehaus.plexus.PlexusContainer - Could not transfer metadata com.example:java-maven-junit-helloworld:1.0.0-SNAPSHOT/maven-metadata.xml from/to snapshots (http://9.42.24.114:8082/artifactory/ida-virtual): Authentication failed for http://9.42.24.114:8081/artifactory/ida-local/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/maven-metadata.xml 401 Unauthorized
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - BUILD FAILURE
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Total time:  23.522 s
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2020-07-31T05:13:04Z
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project java-maven-junit-helloworld: Failed to retrieve remote metadata com.example:java-maven-junit-helloworld:1.0.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata com.example:java-maven-junit-helloworld:1.0.0-SNAPSHOT/maven-metadata.xml from/to snapshots (http://9.42.24.114:8082/artifactory/ida-virtual): Authentication failed for http://9.42.24.114:8081/artifactory/ida-local/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/maven-metadata.xml 401 Unauthorized -> [Help 1]
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
[main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
[main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ERROR: Build step failed with exception
java.lang.RuntimeException: Maven build failed
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:233)
	at org.jfrog.hudson.maven3.Maven3Builder.RunMaven(Maven3Builder.java:115)
	at org.jfrog.hudson.maven3.Maven3Builder.perform(Maven3Builder.java:95)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1880)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Invoke Artifactory Maven 3' marked build as failure
Archiving artifacts

```

Changes since last successful build:
No changes

[View full output](http://9.42.24.114:8888/job/java-maven/5/)

**Comment by ramprasadgk** [comment]
Build was fixed!
