### ISSUE TITLE
java-maven #14 failed

### ISSUE THREAD

**Issue by ramprasadgk** [ramprasadgk/java-maven#25]
Build 'java-maven' is failing!

Last 50 lines of build output:

```
[...truncated 9.88 KB...]
[main] INFO org.jacoco.maven.MergeMojo - Loading execution data file /var/jenkins_home/workspace/java-maven/target/jacoco.exec
[main] INFO org.jacoco.maven.MergeMojo - Loading execution data file /var/jenkins_home/workspace/java-maven/target/jacoco-it.exec
[main] INFO org.jacoco.maven.MergeMojo - Loading execution data file /var/jenkins_home/workspace/java-maven/target/jacoco-both.exec
[main] INFO org.jacoco.maven.MergeMojo - Writing merged execution data to /var/jenkins_home/workspace/java-maven/target/jacoco-both.exec
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- jacoco-maven-plugin:0.8.1:report-integration (jacoco-integration) @ java-maven-junit-helloworld ---
[main] INFO org.jacoco.maven.ReportITMojo - Loading execution data file /var/jenkins_home/workspace/java-maven/target/jacoco-it.exec
[main] INFO org.jacoco.maven.ReportITMojo - Analyzed bundle 'java-maven-junit-helloworld' with 2 classes
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- jacoco-maven-plugin:0.8.1:report (jacoco-reportboth) @ java-maven-junit-helloworld ---
[main] INFO org.jacoco.maven.ReportMojo - Loading execution data file /var/jenkins_home/workspace/java-maven/target/jacoco-both.exec
[main] INFO org.jacoco.maven.ReportMojo - Analyzed bundle 'java-maven-junit-helloworld' with 2 classes
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-install-plugin:2.4:install (default-install) @ java-maven-junit-helloworld ---
[main] INFO org.codehaus.plexus.PlexusContainer - Installing /var/jenkins_home/workspace/java-maven/target/java-maven-junit-helloworld-1.0.0-SNAPSHOT.jar to /var/jenkins_home/.m2/repository/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/java-maven-junit-helloworld-1.0.0-SNAPSHOT.jar
[main] INFO org.codehaus.plexus.PlexusContainer - Installing /var/jenkins_home/workspace/java-maven/pom.xml to /var/jenkins_home/.m2/repository/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/java-maven-junit-helloworld-1.0.0-SNAPSHOT.pom
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-deploy-plugin:2.7:deploy (default-deploy) @ java-maven-junit-helloworld ---
Downloading from snapshots: http://9.42.24.114:8082/artifactory/ida-virtual/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/maven-metadata.xml
[main] WARNING org.codehaus.plexus.PlexusContainer - Could not transfer metadata com.example:java-maven-junit-helloworld:1.0.0-SNAPSHOT/maven-metadata.xml from/to snapshots (http://9.42.24.114:8082/artifactory/ida-virtual): Authentication failed for http://9.42.24.114:8081/artifactory/ida-local/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/maven-metadata.xml 401 Unauthorized
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - BUILD FAILURE
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Total time:  7.501 s
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2020-07-31T11:29:21Z
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project java-maven-junit-helloworld: Failed to retrieve remote metadata com.example:java-maven-junit-helloworld:1.0.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata com.example:java-maven-junit-helloworld:1.0.0-SNAPSHOT/maven-metadata.xml from/to snapshots (http://9.42.24.114:8082/artifactory/ida-virtual): Authentication failed for http://9.42.24.114:8081/artifactory/ida-local/com/example/java-maven-junit-helloworld/1.0.0-SNAPSHOT/maven-metadata.xml 401 Unauthorized -> [Help 1]
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
[main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
[main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ERROR: Build step failed with exception
java.lang.RuntimeException: Maven build failed
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:233)
	at org.jfrog.hudson.maven3.Maven3Builder.RunMaven(Maven3Builder.java:115)
	at org.jfrog.hudson.maven3.Maven3Builder.perform(Maven3Builder.java:95)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1880)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Invoke Artifactory Maven 3' marked build as failure
Archiving artifacts

```

Changes since last successful build:
No changes

[View full output](http://9.42.24.114:8888/job/java-maven/14/)

**Comment by ramprasadgk** [comment]
Build was fixed!
